
online: true

logging.config: classpath:log-prod.xml

server.port: 8787

spring.application.name: web-manager


spring:
#  session:
#    store-type: redis
#  redis:
#    host: 127.0.0.1
#    port: 6379
  http.multipart:
    maxFileSize: 12Mb
    maxRequestSize: 20Mb


spring.dubbo:
  scan: com.github
  application:
    name: ${spring.application.name}
    registry:
      address: zookeeper://192.168.1.100:2181
      timeout: 10000
      register: false
    registries:
      -
        address: zookeeper://192.168.1.101:2181
        timeout: 10000
        register: false
      -
        address: zookeeper://192.168.1.102:2181
        timeout: 10000
        register: false
