
online: true

logging.config: classpath:log-prod.xml

server.port: 8787
spring.application.name: web-backend

spring.redis:
  host: 127.0.0.1
  port: 6379

spring.dubbo:
  scan: com.github
  application:
    name: ${spring.application.name}
    registries:
      -
        address: zookeeper://127.0.0.1:2181
        timeout: 10000
        register: false
