
online: false

logging.config: classpath:log-test.xml

spring.application.name: search

spring.redis:
  host: 127.0.0.1
  port: 6379

spring.dubbo:
  scan: com.github
  protocol:
    name: dubbo
    port: 20872
    serialization: kryo
  application:
    name: ${spring.application.name}
    registry:
      address: zookeeper://test_zk_ip:test_zk_port
      timeout: 10000
