
online: false

logging.config: classpath:log-test.xml

server.port: 8002

spring.redis:
  host: 127.0.0.1
  port: 6379

spring.dubbo:
  scan: com.github
  application:
    name: web-platform
    registry:
      address: zookeeper://127.0.0.1:2181
      timeout: 10000
      register: false

