
database:
  url:  jdbc:mysql://test_db:test_port/x123x?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&statementInterceptors=com.github.common.sql.ShowSqlInterceptor
  userName: xx123xx
  password: xxx123xxx
  initialSize: 2
  minIdle: 2
  maxActive: 10
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  filters: stat,wall

spring.redis:
  host: test_redis
  port: 6379

spring.dubbo:
  scan: com.github
  protocol:
    name: dubbo
    port: 20870
    serialization: kryo
  application:
    name: ${spring.application.name}
    registry:
      address: zookeeper://test_zk:test_zk_port
      timeout: 10000
