
database:
  url: jdbc:mysql://prod_db_order:3306/order?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
  userName: prod_order_user
  password: prod_order_pass
  initialSize: 10
  minIdle: 10
  maxActive: 100
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  filters: wall

spring.redis:
  host: prod_redis
  port: 6379

spring.dubbo:
  scan: com.github
  protocol:
    name: dubbo
    port: 20883
  application:
    name: ${spring.application.name}
    registry:
      address: zookeeper://prod_zk1:2181
      timeout: 10000
    registries:
      -
        address: zookeeper://prod_zk2:2181
        timeout: 10000
      -
        address: zookeeper://prod_zk3:2181
        timeout: 10000
