
spring.activemq:
  broker-url: failover:(tcp://prod_queue1:61616,tcp://prod_queue2:61616)?timeout=3000&startupMaxReconnectAttempts=5
  user: admin
  password: admin
  pool:
    enabled: true
    max-connections: 10
