
spring.dubbo:
  scan: com.github
  protocol:
    name: dubbo
    port: 20871
  application:
    name: ${spring.application.name}
    registry:
      address: zookeeper://test-zk1:2181
      timeout: 10000
    registries:
      -
        address: zookeeper://test-zk2:2182
        timeout: 10000
      -
        address: zookeeper://test-zk3:2183
        timeout: 10000
