
search.ip-port: dev-search:9200

database:
  url:  jdbc:mysql://dev-db-search:3306/search-db-dev?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&statementInterceptors=com.github.common.sql.ShowSqlInterceptor
  userName: root
  password: root
  initialSize: 1
  minIdle: 1
  maxActive: 1
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  filters: stat,wall
