
spring.dubbo:
  scan: com.github
  application:
    name: ${spring.application.name}
    registry:
      address: zookeeper://zk.test:2181
      timeout: 10000
      register: false
    registries:
      -
        address: zookeeper://zk.test:2182
        timeout: 10000
        register: false
      -
        address: zookeeper://zk.test:2183
        timeout: 10000
        register: false
