
online: true

logging.config: classpath:log-prod.xml

spring.application.name: message


spring.activemq:
  broker-url: failover:(tcp://first:61616,tcp://secondary:61616)?timeout=3000&startupMaxReconnectAttempts=5
  user: admin
  password: admin
  pool:
    enabled: true
    max-connections: 10


spring.dubbo:
  scan: com.github
  protocol:
    name: dubbo
    port: 20871
    serialization: kryo
  application:
    name: ${spring.application.name}
    registry:
      address: zookeeper://192.168.1.100:2181
      timeout: 10000
    registries:
      -
        address: zookeeper://192.168.1.101:2181
        timeout: 10000
      -
        address: zookeeper://192.168.1.102:2181
        timeout: 10000
