
# 线上环境

online: true

logging.config: classpath:log-prod.xml

spring.application.name: subscribe-message

spring:
  activemq:
    broker-url: failover:(tcp://first:61616,tcp://secondary:61616)?timeout=3000&startupMaxReconnectAttempts=5
    user: admin
    password: admin
  mail:
    host: smtp.yyy.com
    port: 587
    username: abc@yyy.com
    password: xxx

spring.dubbo:
  scan: com.github
  application:
    name: ${spring.application.name}
    registry:
      address: zookeeper://192.168.1.100:2181
      timeout: 10000
      register: false
    registries:
      -
        address: zookeeper://192.168.1.101:2181
        timeout: 10000
        register: false
      -
        address: zookeeper://192.168.1.102:2181
        timeout: 10000
        register: false
