
# 测试环境

online: false

logging.config: classpath:log-test.xml

spring.application.name: subscribe-message

spring:
  activemq:
    broker-url: failover:(tcp://ip:port)?timeout=3000&startupMaxReconnectAttempts=5
    user: admin
    password: admin
  mail:
    host: smtp.yyy.com
    port: 587
    username: abc@yyy.com
    password: xxx


spring.dubbo:
  scan: com.github
  application:
    name: ${spring.application.name}
    registry:
      address: zookeeper://127.0.0.1:2181
      timeout: 10000
      register: false
