
online: false

logging.config: classpath:log-dev.xml

server.port: 8686

spring:
  mvc.throw-exception-if-no-handler-found: true
  resources.add-mappings: false


# 让 FeignClient 的断路器生效
# feign.hystrix.enabled: true

# 路由
zuul:
  routes:
    # 公共模块
    common:
      path: /common/**
      serviceId: common
      stripPrefix: false
    # 用户模块
    user:
      path: /user/**
      serviceId: user
      stripPrefix: false
    # 商品模块
    product:
      path: /product/**
      serviceId: product
      stripPrefix: false
    # 交易模块
    trade:
      path: /trade/**
      serviceId: trade
      stripPrefix: false

## org.springframework.cloud.sleuth.zipkin2.ZipkinProperties
#spring:
#  zipkin.base-url: http://127.0.0.1:9411
#  # 抽样比例, 默认是 10%, 如果 值是 1 则表示 100%, 分页式追踪数据量可能会非常大
#  sleuth.sampler.percentage: 0.1
