
online: true

logging.config: classpath:log-prod.xml

server.port: 8686

spring:
  application.name: web-backend
  mvc.throw-exception-if-no-handler-found: true
  resources.add-mappings: false

spring.dubbo:
  scan: com.github
  application:
    name: ${spring.application.name}
    registries:
      -
        address: zookeeper://192.168.1.101:2181
        timeout: 10000
        register: false
      -
        address: zookeeper://192.168.1.102:2181
        timeout: 10000
        register: false

#spring:
#  zipkin.base-url: http://127.0.0.1:9411
#  sleuth.sampler.percentage: 0.1
