
online: false

logging.config: classpath:log-dev.xml

server.port: 8686

spring:
  application.name: web-backend
  mvc.throw-exception-if-no-handler-found: true
  resources.add-mappings: false


spring:
#  session:
#    store-type: redis
#  redis:
#    host: 127.0.0.1
#    port: 6379
  http.multipart:
    maxFileSize: 12Mb
    maxRequestSize: 20Mb


spring.dubbo:
  scan: com.github
  application:
    name: ${spring.application.name}
    registry:
      address: zookeeper://127.0.0.1:2181
      timeout: 10000
      register: false
